name: Publish release to Maven Central
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Please, enter a version name"
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Publish Library to Maven Central
        run: |
          echo "Publishing the Library 🚀"
          VERSION=${{ github.event.inputs.versionName }}
          echo "Version name $VERSION"
          ./gradlew publishAndReleaseToMavenCentral -PlibraryVersion=VERSION --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.inputs.versionName }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
